version: "3"
services:
  postgredb:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      
  redis:
    image: redis:6
    ports:
      - 6379:6379

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    depends_on: 
      - postgres