version: "3"
services:
  app:
    build: ./app
    ports:
      - 8080:8080
    environment:
      - PG_CONN_STRING=${PG_CONN_STRING}
      - REDIS_ADDR=${REDIS_ADRESS}
    depends_on:
      - redis
      - postgredb
      
  jobscheduler:
    build: ./jobscheduler
    environment:
      - PG_CONN_STRING=${PG_CONN_STRING}
      - REDIS_ADDR=${REDIS_ADRESS}
    depends_on:
      - redis
      - postgredb

  postgredb:
    build: ./postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gospy
      
  redis:
    image: redis:6
    ports:
      - 6379:6379

  asynqadmin:
    image: hibiken/asynqmon
    ports:
      - 8082:8080
    environment:
      - REDIS_ADDR=${REDIS_ADRESS}
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    depends_on: 
      - postgredb